// ============================================================
// assignments.js
//
// The list of reflection assignments students can choose from.
// Each entry is { name, length, prompts } where:
//   - "length"  is the minimum number of minutes before the
//     submit button unlocks.
//   - "prompts" is an array of prompt strings specific to that
//     film. While writing, students can click a "Show a prompt"
//     button to get a random one (shuffled, no repeats until the
//     list runs out). This is just the *starting* list — students
//     can also contribute additional prompts for a film after
//     they submit their own reflection for it; those get pulled
//     from Firestore (the "promptSubmissions" collection) and
//     merged in alongside these whenever the film is selected.
//
// Edit this array directly to add, remove, rename, or re-time
// assignments, or to add/edit prompts — no Firestore console
// work needed for any of that.
// ============================================================

export const assignments = [
  { name: "Test 1", length: 1, prompts: []},
  { name: "Test 2", length: 1, prompts: []},
  { name: "Jaws", length: 15, prompts: [
    "this is a movie about fear",
    "this is a movie about masculinity",
    "this is a movie about the ocean",
    "this is a movie about a community in denial",
    "this is a movie about protecting people who refuse to protect themselves",
    "this is a movie about the failure of institutions",
    "this is a movie about the fear of the unknown",
    "this is a movie about nature refusing to be controlled",
    "this is a movie about obsession",
    "this is a movie about responsibility",
    "this is a movie about money versus human life",
    "this is a movie about three men confronting the same fear in different ways",
    "this is a movie about what happens when fear becomes political",
    "this is a movie about turning a monster into a myth",
    "this is a movie about the consequences of underestimating danger",
    "What does John Williams' two-note theme make you feel before you ever see the shark?",
    "Why does the shark itself stay silent while everything around it has music?",
    "What is missing from the sound design during the first attack on Chrissie, and what does that absence do?",
    "How does the score change once the Orca sets out to hunt, compared to when it was only warning of danger?"
  ] },
  { name: "Candyman", length: 15, prompts: [
    "this is a movie about urban legends",
    "this is a movie about racism",
    "this is a movie about gentrification",
    "this is a movie about the stories people tell about each other",
    "this is a movie about the power of belief",
    "this is a movie about grief",
    "this is a movie about class",
    "this is a movie about violence becoming folklore",
    "this is a movie about the history hidden inside a neighborhood",
    "this is a movie about obsession",
    "this is a movie about the relationship between art and horror",
    "this is a movie about turning trauma into mythology",
    "this is a movie about the danger of treating suffering as entertainment",
    "this is a movie about a monster who exists because people remember him",
    "this is a movie about the relationship between memory and violence",
    "What happens in your body when the choir swells during the mirror chant?",
    "Why does Philip Glass's score sound almost beautiful for a story this violent?",
    "What is the effect of the organ and bells recurring throughout the film?",
    "How does the sound design shift in the hive/bee scenes compared to everywhere else in the film?"
  ] },
  { name: "Pontypool", length: 15, prompts: [
    "this is a movie about language",
    "this is a movie about communication",
    "this is a movie about the power of words",
    "this is a movie about isolation",
    "this is a movie about the fear of losing your ability to communicate",
    "this is a movie about mass panic",
    "this is a movie about the media",
    "this is a movie about misinformation",
    "this is a movie about trying to understand a crisis while it is happening",
    "this is a movie about language as a virus",
    "this is a movie about the limitations of technology",
    "this is a movie about the difference between hearing something and understanding it",
    "this is a movie about how quickly meaning can become meaningless",
    "this is a movie about the intimacy of voices without bodies",
    "this is a movie about the danger of misunderstanding",
    "What does it do to you as a viewer to experience most of the crisis only through Grant Mazzy's voice?",
    "Why does the film keep so much of the violence offscreen, delivered instead through radio dispatches?",
    "What is unsettling about the moment language itself starts to malfunction on air?",
    "How does the film build claustrophobia inside the radio booth using only sound?",
    "What does it mean that all the theories the characters have seem to be just…wrong?",
    "What does the post-credit scene mean (if you saw it)?"
  ] },
  { name: "Psycho", length: 15, prompts: [
    "this is a movie about guilt",
    "this is a movie about repression",
    "this is a movie about voyeurism",
    "this is a movie about loneliness",
    "this is a movie about desire",
    "this is a movie about secrets",
    "this is a movie about identity",
    "this is a movie about the fear of being watched",
    "this is a movie about the things people do when they think nobody is looking",
    "this is a movie about a mother and son",
    "this is a movie about appearances",
    "this is a movie about the instability of identity",
    "this is a movie about ordinary people making terrible decisions",
    "this is a movie about turning domestic spaces into places of terror",
    "this is a movie about the consequences of trying to escape your past",
    "What do Bernard Herrmann's shrieking strings do in the shower scene that images alone couldn't?",
    "Why is there no score at all during Marion's long drive, alone with her thoughts?",
    "What effect does the sudden silence right after the shower scene have on you?",
    "How does the sound of Mother's voice work on you before you ever see her?"
  ] },
  { name: "From Dusk Till Dawn", length: 15, prompts: [
    "this is a movie about criminals",
    "this is a movie about brotherhood",
    "this is a movie about loyalty",
    "this is a movie about violence",
    "this is a movie about sudden changes in genre",
    "this is a movie about bad people being forced to do good things",
    "this is a movie about masculinity",
    "this is a movie about faith",
    "this is a movie about survival",
    "this is a movie about strangers becoming a team",
    "this is a movie about the line between predator and prey",
    "this is a movie about exploitation",
    "this is a movie about chaos",
    "this is a movie about discovering that the situation is much worse than you thought",
    "this is a movie about the unexpected rules of survival",
    "What is the function of the music and dancing in the Titty Twister right before everything turns violent?",
    "How does the film use a shift in soundtrack to announce that it has suddenly become a different genre?",
    "What does the mariachi/rock soundtrack tell you about the world these characters are walking into?"
  ] },
  { name: "The Shining", length: 15, prompts: [
    "the author of the book (Stephen King) hated this movie",
    "this is a movie about domestic violence",
    "this is a movie about alcoholism",
    "this is a movie about isolation",
    "this is a movie about the challenges of being creative under pressure",
    "this is a movie about the destruction of a family",
    "this is a movie about masculinity",
    "this is a movie about rage",
    "this is a movie about addiction",
    "this is a movie about loneliness",
    "this is a movie about psychological abuse",
    "this is a movie about generational trauma",
    "this is a movie about the past refusing to stay buried",
    "this is a movie about a man failing to become the person he wants to be",
    "this is a movie about the impossibility of escaping yourself",
    "this is a movie about the relationship between madness and creativity",
    "What is unsettling about the way \"Midnight, the Stars and You\" plays over the final shot?",
    "How does Wendy Carlos and Rachel Elkind's score use dissonance to make empty hallways feel dangerous?",
    "What effect does the sound of Danny's tricycle wheels have as it shifts between carpet and floor?",
    "Why is the sound of the typewriter used the way it is throughout the film?"
  ] },
  { name: "Room 237", length: 15, prompts: [
    "this is a movie about paralleling the structure of The Shining",
    "this is a movie about interpreting movies",
    "this is a movie about conspiracy theories",
    "this is a movie about obsession",
    "this is a movie about seeing patterns everywhere",
    "this is a movie about the gap between intention and interpretation",
    "this is a movie about the audience taking control of a work",
    "this is a movie about how much meaning we can project onto images",
    "this is a movie about paranoia",
    "this is a movie about Kubrick",
    "this is a movie about the mythology surrounding great art",
    "this is a movie about the difference between analysis and obsession",
    "this is a movie about trying to solve a movie like a puzzle",
    "this is a movie about the desire to believe there is a hidden answer",
    "this is a movie about the relationship between art and interpretation",
    "What happens when the same score and sound cues from The Shining get reinterpreted by each narrator's theory?",
    "How does hearing multiple voices talk over the same scene change how you experience it?",
    "What does it mean that this documentary has no on-camera interviews, only voices layered over footage?"
  ] },
  { name: "Funny Games", length: 15, prompts: [
    "this is a movie where the director hates the audience",
    "this is a movie that you're supposed to hate",
    "this is a movie about violence as entertainment",
    "this is a movie about the audience's complicity",
    "this is a movie about privilege",
    "this is a movie about boredom",
    "this is a movie about cruelty",
    "this is a movie about power",
    "this is a movie about the rules of horror movies",
    "this is a movie about what audiences expect from violence",
    "this is a movie about breaking the contract between a movie and its audience",
    "this is a movie about sadism",
    "this is a movie about class conflict",
    "this is a movie about helplessness",
    "this is a movie about controlling the story",
    "this is a movie about making the audience feel responsible for what they watch",
    "this is a movie about the morality of watching violence",
    "Why does the film open with genteel classical music laid against the harshness of the opening credits?",
    "What is the effect of the remote-control \"rewind\" moment on the soundtrack and on your sense of control as a viewer?",
    "Why do the killers seem to control not just the story but the soundtrack itself?"
  ] },
  { name: "American Psycho", length: 15, prompts: [
    "this is a movie about capitalism",
    "this is a movie about toxic masculinity",
    "this is a movie about consumerism",
    "this is a movie about status",
    "this is a movie about loneliness",
    "this is a movie about narcissism",
    "this is a movie about identity",
    "this is a movie about the performance of success",
    "this is a movie about a man who has everything and feels nothing",
    "this is a movie about violence as a form of power",
    "this is a movie about conformity",
    "this is a movie about the emptiness behind wealth",
    "this is a movie about confusing possessions with personality",
    "this is a movie about a society that cannot recognize a monster because he looks successful",
    "this is a movie about the relationship between identity and performance",
    "What does it mean that Bateman narrates his taste in pop music right before he kills someone?",
    "How does the upbeat soundtrack make his violence feel even more unsettling?",
    "What is the effect of the music cutting out during his most disturbing acts?"
  ] },
  { name: "The Cell", length: 15, prompts: [
    "this is a movie about the imagination",
    "this is a movie about trauma",
    "this is a movie about entering someone else's mind",
    "this is a movie about empathy",
    "this is a movie about identity",
    "this is a movie about childhood and the challenges of overcoming past trauma",
    "this is a movie about the relationship between beauty and horror",
    "this is a movie about the psychology of a killer",
    "this is a movie about trying to save someone who cannot save themselves",
    "this is a movie about the unconscious",
    "this is a movie about the danger of becoming fascinated by evil",
    "this is a movie about finding humanity inside a monster",
    "this is a movie about the mind as a place you can get lost",
    "this is a movie about the boundary between empathy and identification",
    "How does the sound design shift the moment we enter the killer's mind?",
    "What effect do the operatic and choral elements have during the dream sequences?",
    "Why does the film pair such beautiful sound and imagery with such disturbing content?"
  ] },
  {
  "name": "Raw",
  "length": 15,
  "prompts": [
    "This is a movie about becoming an adult",
    "This is a movie about sisterhood",
    "This is a movie about sexuality",
    "This is a movie about hunger",
    "This is a movie about bodily transformation",
    "This is a movie about discovering who you are",
    "This is a movie about family secrets",
    "This is a movie about the pressure to conform",
    "This is a movie about rebellion",
    "This is a movie about desire",
    "This is a movie about the fear of becoming like your parents",
    "This is a movie about the complicated relationship between love and cruelty",
    "This is a movie about finding freedom through losing control",
    "This is a film about the body becoming something unfamiliar",
    "This is a film about learning to accept the parts of yourself you were taught to suppress",
    "What is the function of the pulsing party music during the hazing scenes?",
    "How does sound, or the withdrawal of it, mark the moments when Justine loses control?",
    "What effect does the music have on the tension during the waxing scene?"
  ] },
  { name: "Pan's Labyrinth", length: 15, prompts: [
    "this is a movie about childhood",
    "this is a movie about female identity",
    "this is a movie about fascism",
    "this is a movie about imagination",
    "this is a movie about obedience",
    "this is a movie about disobedience",
    "this is a movie about the need to escape reality",
    "this is a movie about the stories we tell ourselves to survive",
    "this is a movie about innocence confronting violence",
    "this is a movie about motherhood",
    "this is a movie about sacrifice",
    "this is a movie about the relationship between fantasy and history",
    "this is a movie about choosing what kind of person you want to be",
    "this is a movie about the brutality of adults seen through a child's eyes",
    "this is a movie about refusing to obey evil",
    "this is a movie about the cost of innocence",
    "What does the lullaby motif suggest about Ofelia's relationship to fantasy and danger?",
    "Why is the Pale Man's lair almost completely silent until it suddenly isn't?",
    "How does the score shift between the fascist real world and Ofelia's fantasy world?"
  ] },
  { name: "Eraserhead", length: 15, prompts: [
    "this is a movie about fatherhood",
    "this is a movie about anxiety",
    "this is a movie about industrialization",
    "this is a movie about parenthood as horror",
    "this is a movie about loneliness",
    "this is a movie about sexual anxiety",
    "this is a movie about responsibility",
    "this is a movie about fear of adulthood",
    "this is a movie about the terror of being trapped by your own life",
    "this is a movie about the fear of having a child",
    "this is a movie about alienation",
    "this is a movie about the body",
    "this is a movie about domestic life becoming surreal",
    "this is a movie about being unable to escape responsibility",
    "this is a movie about the fear of becoming a parent",
    "What is the effect of the constant industrial drone running underneath nearly every scene?",
    "Why does \"In Heaven\" sound so warped and unsettling despite being sung as a lullaby?",
    "How does the sound of the baby's cries dictate the emotional rhythm of the film?"
  ] },
  { name: "The Burbs", length: 15, prompts: [
    "this is a movie about suburban paranoia",
    "this is a movie about boredom",
    "this is a movie about nosiness",
    "this is a movie about communityn and fitting in",
    "this is a movie about suspicion",
    "this is a movie about the fear of your neighbors",
    "this is a movie about suburban conformity",
    "this is a movie about the need to believe something interesting is happening",
    "this is a movie about masculinity",
    "this is a movie about friendship",
    "this is a movie about the fantasy of knowing what happens behind closed doors",
    "this is a movie about ordinary life becoming an adventure",
    "this is a movie about paranoia turning into obsession",
    "this is a movie about how little we really know our neighbors",
    "this is a movie about the desire to escape ordinary life",
    "How does the score signal that this is a comedy even when the imagery suggests horror?",
    "What is the effect of the exaggerated suburban sound design, the lawnmowers, sirens, and barking dogs?",
    "How do subtle sound effects show up throughout the movie? Do they make it seem more like a cartoon?",
    "What does the inclusion of famous Hollywood jumpscares do for the dream sequence?"
  ] },
  { name: "The Exorcist", length: 15, prompts: [
    "this is a movie about doubt",
    "this is a movie about motherhood",
    "this is a movie about guilt",
    "this is a movie about grief",
    "this is a movie about evil",
    "this is a movie about the limits of science",
    "this is a movie about the fear of losing your child",
    "this is a movie about a crisis of faith",
    "this is a movie about sacrifice",
    "this is a movie about helplessness",
    "this is a movie about trying to find meaning in suffering",
    "this is a movie about the conflict between reason and belief",
    "this is a movie about what people are willing to do when they believe someone they love is possessed",
    "this is a movie about the terror of losing control of someone you love",
    "What effect does Mike Oldfield's \"Tubular Bells\" have on you before anything frightening even happens?",
    "How does Regan's voice change over the course of the film, and what does that transformation do to you?",
    "Why is the sound of scraping and knocking in the attic more disturbing than a jump scare would be?"
  ] },
  { name: "Mandy", length: 15, prompts: [
    "this is a movie about grief",
    "this is a movie about revenge",
    "this is a movie about love",
    "this is a movie about masculinity",
    "this is a movie about trauma",
    "this is a movie about psychedelic horror",
    "this is a movie about turning pain into violence",
    "this is a movie about obsession",
    "this is a movie about the fantasy of revenge",
    "this is a movie about a man consumed by grief",
    "this is a movie about evil",
    "this is a movie about the power of memory",
    "this is a movie about losing the person who gives your life meaning",
    "this is a movie about becoming a monster to kill a monster",
    "this is a movie about grief as a source of power",
    "What does Jóhann Jóhannsson's droning score do to you during the chainsaw duel?",
    "How does the film use sound distortion to represent Red's descent into grief and vengeance?",
    "What is the effect of the tone of the fake Cheddar Goblin commercial compared to the rest of the film?"
  ] },
  { name: "Silence of the Lambs", length: 15, prompts: [
    "this is a movie about fear",
    "this is a movie about intelligence",
    "this is a movie about power",
    "this is a movie about gender",
    "this is a movie about trauma",
    "this is a movie about ambition",
    "this is a movie about manipulation",
    "this is a movie about empathy",
    "this is a movie about understanding a monster",
    "this is a movie about the relationship between victim and predator",
    "this is a movie about a woman navigating a world dominated by men",
    "this is a movie about using vulnerability as strength",
    "this is a movie about the psychology of violence",
    "this is a movie about how understanding evil can become a form of power",
    "this is a movie about the cost of confronting your deepest fears",
    "What is the effect of the near silence during Clarice's descent into Buffalo Bill's basement?",
    "How does the absence of score during the interrogation scenes with Lecter change the tension?",
    "What do you hear, or fail to hear, in the moment right before the lights go out in the basement?"
  ] },
  { name: "Sinners", length: 15, prompts: [
    "this is a movie about community",
    "this is a movie about music",
    "this is a movie about Black history",
    "this is a movie about racism",
    "this is a movie about exploitation",
    "this is a movie about cultural inheritance",
    "this is a movie about brotherhood",
    "this is a movie about the power of music",
    "this is a movie about the things we inherit from our ancestors",
    "this is a movie about temptation",
    "this is a movie about freedom",
    "this is a movie about identity",
    "this is a movie about preserving culture in a world that wants to consume it",
    "this is a movie about the price of trying to escape your past",
    "this is a movie about the relationship between culture and survival",
    "What happens musically in the juke joint scene that connects past, present, and future?",
    "How does the film treat music as something almost supernatural, capable of summoning things?",
    "What is the effect of blending blues, gospel, and other traditions into a single musical moment?"
  ] },
  { name: "Scenic Route", length: 15, prompts: [
    "this is a movie about friendship",
    "this is a movie about masculinity",
    "this is a movie about failure",
    "this is a movie about resentment",
    "this is a movie about survival",
    "this is a movie about regret",
    "this is a movie about the lives we imagine we should have",
    "this is a movie about two friends confronting what they have become",
    "this is a movie about envy",
    "this is a movie about the pressure to succeed",
    "this is a movie about comparing your life to someone else's",
    "this is a movie about being trapped with someone who knows your weaknesses",
    "this is a movie about how friendship changes when life doesn't go according to plan",
    "this is a movie about the difference between surviving and living",
    "this is a movie about the fear of becoming a failure",
    "What is the effect of the desert's silence on the tension between the two friends?",
    "How does the absence of music in most scenes shape the way you experience their arguments?"
  ] },
  { name: "Undertone", length: 15, prompts: [
    "this is a movie about sound",
    "this is a movie about silence",
    "this is a movie about the things left unsaid",
    "this is a movie about intimacy",
    "this is a movie about paranoia",
    "this is a movie about hidden tension",
    "this is a movie about memory",
    "this is a movie about perception",
    "this is a movie about the unreliability of what we hear",
    "this is a movie about the emotional power of sound",
    "this is a movie about secrets",
    "this is a movie about subtext",
    "this is a movie about the fear beneath ordinary life",
    "this is a movie about the difference between what is said and what is meant",
    "this is a movie about the things hiding underneath a conversation",
    "What does the title suggest about the relationship between sound and meaning in this film?",
    "How does the film use silence to communicate what the characters won't say aloud?"
  ] },
  { name: "28 Years Later: The Bone Temple", length: 15, prompts: [
    "this is a movie about challenges of male friendship",
    "this is a movie about civilization",
    "this is a movie about survival",
    "this is a movie about violence",
    "this is a movie about the meaning of humanity",
    "this is a movie about what happens after the apocalypse",
    "this is a movie about community",
    "this is a movie about fear",
    "this is a movie about power",
    "this is a movie about rebuilding society",
    "this is a movie about what people become when the rules disappear",
    "this is a movie about the difference between humans and monsters",
    "this is a movie about inherited trauma",
    "this is a movie about whether civilization is worth preserving",
    "this is a movie about the stories we tell ourselves about survival",
    "this is a movie about what it means to remain human",
    "How does the sound design carry anxieties from the original 28 Days Later into this new world?",
    "What is the effect of using spoken word or poetry within the sound design of a survival horror film?",
    "How does the music mark the difference between the world before and after collapse?"
  ] },
];


// Turns a name into a stable, URL/Firestore-safe id, e.g.
// "The Cell (the 2000 one)" -> "the-cell-the-2000-one"
// Used as the assignment's identifier in Firestore document paths,
// so it must stay consistent between student.js and admin.js
// (both import it from here rather than each defining their own).
export function slugify(name) {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-+|-+$)/g, "");
}