#!/usr/bin/env python3

import json
import re
import sys
from pathlib import Path

from bs4 import BeautifulSoup, Comment, NavigableString
from markdownify import MarkdownConverter

BULLET_MD_SENTINEL = "BULLETMDTIGHTLISTSENTINEL"

# Matches `const SCHEDULE_DATA = [ ... ];` (however it's formatted/indented)
# inside a schedule.js file generated by schedule_csv_to_js.py.
SCHEDULE_DATA_RE = re.compile(r"const\s+SCHEDULE_DATA\s*=\s*(\[.*\])\s*;",
                              re.DOTALL)


def _find_schedule_script_src(soup: BeautifulSoup):
    """Find the external <script src="..."> most likely to define
    SCHEDULE_DATA — i.e. any script tag whose src looks like it points at
    a schedule data file."""
    candidates = []
    for tag in soup.find_all("script", src=True):
        src = tag.get("src") or ""
        if "schedule" in src.lower():
            candidates.append(src)
    return candidates[0] if candidates else None


def _load_schedule_data(base_dir: Path, script_src: str):
    js_path = (base_dir / script_src).resolve()
    if not js_path.is_file():
        return None
    js_text = js_path.read_text(encoding="utf-8")
    match = SCHEDULE_DATA_RE.search(js_text)
    if not match:
        return None
    return json.loads(match.group(1))


def _todo_item_text(item) -> str:
    # Items are either {"text": ..., "url": ...} objects (current format)
    # or bare strings (older schedule.js files) — support both.
    if isinstance(item, dict):
        return item.get("text", "")
    return str(item)


def _todo_item_url(item):
    if isinstance(item, dict):
        return item.get("url")
    return None


def _build_todo_item_html(item) -> str:
    text = _todo_item_text(item)
    url = _todo_item_url(item)
    if url:
        return f'<li><a href="{url}" target="_blank">{text}</a></li>'
    return f"<li>{text}</li>"


def _build_todo_column_html(heading: str, items) -> str:
    if not items:
        return ""
    list_items = "".join(_build_todo_item_html(item) for item in items)
    return (f'<div class="week-column"><h4>{heading}</h4>'
            f'<ul class="check-list">{list_items}</ul></div>')


def _build_week_card_html(week: dict) -> str:
    card_class = week.get("cardClass", "week-card")
    card_classes = f"{card_class} week-card".strip()

    if week.get("fourthHour"):
        todo_items = "".join(
            _build_todo_item_html(item) for item in week.get("todo", []))
        columns_html = (f'<div class="week-column"><h4>To-do in lab</h4>'
                        f'<ul class="check-list">{todo_items}</ul></div>')
    else:
        before_html = _build_todo_column_html("To-do before class",
                                              week.get("todoBeforeClass", []))
        during_html = _build_todo_column_html("To-do in class",
                                              week.get("todoDuringClass", []))
        columns_html = f'<div class="week-columns">{before_html}{during_html}</div>'

    return (f'<article class="{card_classes}">'
            f'<div class="week-number">{week.get("date", "")}</div>'
            f'<div class="week-content">'
            f'<h3>{week.get("title", "")}</h3>'
            f'<p>{week.get("description", "")}</p>'
            f"{columns_html}"
            f"</div>"
            f"</article>")


def inject_schedule_data(soup: BeautifulSoup, base_dir: Path) -> None:
    """The schedule section is populated at runtime by schedule.js
    (renderSchedule() in index.html), not hardcoded in the HTML — so a
    plain read of the HTML sees an empty #week-list. Load schedule.js
    ourselves, rebuild the same week-card markup the page's own JS would
    produce, and splice it into #week-list before the rest of the
    conversion pipeline runs, so the schedule shows up in the markdown."""
    script_src = _find_schedule_script_src(soup)
    if not script_src:
        return

    weeks = _load_schedule_data(base_dir, script_src)
    if weeks is None:
        return

    container = soup.find(id="week-list")
    if container is None:
        return

    container.clear()
    cards_html = "".join(_build_week_card_html(week) for week in weeks)
    fragment = BeautifulSoup(cards_html, "html.parser")
    for child in list(fragment.children):
        container.append(child)


def has_class(tag, *names):
    classes = tag.get("class") or []
    return any(n in classes for n in names)


def has_class_containing(tag, needle):
    classes = tag.get("class") or []
    return any(needle in c for c in classes)


def strip_decorative_and_excluded(soup: BeautifulSoup) -> None:
    for c in soup.find_all(string=lambda s: isinstance(s, Comment)):
        c.extract()

    for tag in soup.find_all(["script", "style"]):
        tag.decompose()

    for tag in soup.find_all("nav"):
        tag.decompose()
    for tag in soup.select("a.skip-link"):
        tag.decompose()

    for tag in soup.find_all(
            lambda t: has_class(t, "minor", "very-minor", "ignore-md")):
        tag.decompose()

    for tag in soup.find_all(lambda t: has_class(t, "ghost")):
        tag.decompose()

    for tag in soup.find_all(lambda t: has_class(t, "arrow")):
        tag.decompose()

    for tag in soup.find_all(attrs={"aria-hidden": "true"}):
        tag.decompose()

    for tag in soup.find_all(["img", "video", "source", "figcaption"]):
        tag.decompose()

    for tag in soup.select("button.modal-close"):
        tag.decompose()

    for modal_id in ("map-modal", "resource-modal", "pyramid-modal"):
        tag = soup.find(id=modal_id)
        if tag is not None:
            tag.decompose()

    for tag in soup.find_all(lambda t: has_class(t, "vertical-buttons")):
        tag.decompose()


def restructure_pyramid_tiers(soup: BeautifulSoup) -> None:
    for tier in soup.find_all(lambda t: has_class(t, "pyramid-tier")):
        points_el = tier.find(class_="pyramid-points")
        title_el = tier.find(class_="pyramid-title")
        points = points_el.get_text(strip=True) if points_el else ""
        title = title_el.get_text(strip=True) if title_el else ""

        keep_list = tier.find(
            "ul",
            class_=lambda c: c and "pyramid-tier-data" in c and "check-list" in
            c,
        )

        heading = soup.new_tag("h3")
        heading.string = f"Tier {points}: {title}" if points else title

        new_container = soup.new_tag("div")
        new_container.append(heading)
        if keep_list is not None:
            new_container.append(keep_list.extract())

        tier.replace_with(new_container)


def clean_resource_cards(soup: BeautifulSoup) -> None:
    for card in soup.find_all(lambda t: has_class(t, "resource-card")):
        label = card.find(class_="resource-label")
        if label is not None:
            p = soup.new_tag("p")
            em = soup.new_tag("em")
            em.string = label.get_text(strip=True)
            p.append(em)
            label.replace_with(p)


def clean_week_numbers(soup: BeautifulSoup) -> None:
    for wn in soup.find_all(lambda t: has_class(t, "week-number")):
        text = wn.get_text(strip=True)
        if not text:
            continue
        hr = soup.new_tag("hr")
        heading = soup.new_tag("h1")
        heading.string = text
        wn.clear()
        wn.append(hr)
        wn.append(heading)


def clean_tag_rows(soup: BeautifulSoup) -> None:
    for row in soup.find_all(lambda t: has_class(t, "tag-row")):
        labels = [
            c.get_text(strip=True) for c in row.find_all(recursive=False)
        ]
        labels = [l for l in labels if l]
        p = soup.new_tag("p")
        em = soup.new_tag("em")
        em.string = ", ".join(labels)
        p.append(em)
        row.clear()
        row.append(p)


def _is_empty_wrapper(node) -> bool:
    return not node.get_text(strip=True) and not node.find(True)


def _is_spacer(node) -> bool:
    return (isinstance(node, NavigableString)
            and not node.strip()) or (getattr(node, "name", None) == "br")


def _climb_out_of_lists(el):
    """Walk up while the parent is a <li>/<ul>/<ol>, returning the
    outermost such ancestor (or `el` itself if it isn't list-nested)."""
    node = el
    while node.parent is not None and getattr(node.parent, "name",
                                              None) in ("li", "ul", "ol"):
        node = node.parent
    return node


def _build_ul(soup, run):
    ul = soup.new_tag("ul")
    for el in run:
        li = soup.new_tag("li")
        for child in list(el.children):
            li.append(child.extract())
        ul.append(li)
    return ul


def _insert_run(soup, anchor, run):
    prev_sib = anchor.previous_sibling
    prev_is_heading = getattr(prev_sib, "name",
                              None) in ("h1", "h2", "h3", "h4", "h5", "h6")

    ul = _build_ul(soup, run)
    anchor.insert_before(ul)
    if prev_is_heading:
        ul.insert_before(NavigableString(BULLET_MD_SENTINEL))
    for el in run:
        el.decompose()


def _merge_bullet_md_tabbed(soup: BeautifulSoup, class_name: str) -> None:
    """Merge runs of directly-adjacent (sibling) elements, preserving
    whatever nesting they already sit inside."""
    processed = set()
    for start in soup.find_all(lambda t: has_class(t, class_name)):
        if id(start) in processed:
            continue

        run = [start]
        processed.add(id(start))
        node = start
        while True:
            spacers = []
            nxt = node.next_sibling
            while nxt is not None and _is_spacer(nxt):
                spacers.append(nxt)
                nxt = nxt.next_sibling
            if nxt is not None and getattr(nxt, "name", None) and has_class(
                    nxt, class_name):
                for sp in spacers:
                    sp.extract()
                run.append(nxt)
                processed.add(id(nxt))
                node = nxt
            else:
                break

        for edge, direction in ((run[0], "previous_sibling"),
                                (run[-1], "next_sibling")):
            sib = getattr(edge, direction)
            while sib is not None and _is_spacer(sib):
                doomed = sib
                sib = getattr(sib, direction)
                doomed.extract()

        _insert_run(soup, run[0], run)


def _merge_bullet_md_untabbed(soup: BeautifulSoup, class_name: str) -> None:
    """Merge every matching element into a single flat <ul>, regardless of
    how deeply nested (tabbed) it is inside other lists.

    A matching element's *row* is its outermost enclosing <li>/<ul>/<ol>
    ("root") that isn't itself shared with an unrelated part of the
    document — concretely, the highest list-item container that holds
    only content belonging to this bullet run. All of that row's
    meaningful children (not just the ones explicitly tagged) become
    entries in the flat list, in document order, so an untagged "leading"
    span in the same row as a tagged one is carried along with it rather
    than left behind. Rows are then processed in document order, and rows
    that are themselves adjacent siblings (separated only by whitespace)
    are merged into one contiguous run/list.
    """
    matches = soup.find_all(lambda t: has_class(t, class_name))
    if not matches:
        return

    # Map each match to the immediate <li> ancestor that directly holds it
    # (its "row"); fall back to the match itself if it isn't inside an <li>.
    def find_li_ancestor(el):
        node = el.parent
        while node is not None and getattr(node, "name", None) != "li":
            node = node.parent
        return node

    rows = []  # ordered, de-duplicated list of row containers
    seen_rows = set()
    match_by_row = {}
    for m in matches:
        li = find_li_ancestor(m)
        row = li if li is not None else m
        key = id(row)
        if key not in seen_rows:
            seen_rows.add(key)
            rows.append(row)
            match_by_row[key] = []
        match_by_row[key].append(m)

    # Climb each row out of any further list nesting to find the true
    # top-level anchor point, and group rows sharing the same outer root.
    root_groups = []  # [{"root": Tag, "rows": [Tag, ...]}]
    root_lookup = {}
    for row in rows:
        root = _climb_out_of_lists(row)
        key = id(root)
        group = root_lookup.get(key)
        if group is None:
            group = {"root": root, "rows": []}
            root_lookup[key] = group
            root_groups.append(group)
        group["rows"].append(row)

    merged_root = root_groups[0]["root"]

    # Build the flat run: for each row (in document order), take every
    # direct child that carries real content (tagged or not) as one entry.
    run = []
    for row in rows:
        if getattr(row, "name", None) == "li":
            children = [c for c in row.find_all(recursive=False)]
            if not children:
                children = [row]
        else:
            children = [row]
        for child in children:
            if isinstance(child, NavigableString):
                continue
            if child.get_text(strip=True) or child.find(True):
                run.append(child)

    for direction in ("previous_sibling", "next_sibling"):
        sib = getattr(merged_root, direction)
        while sib is not None and _is_spacer(sib):
            doomed = sib
            sib = getattr(sib, direction)
            doomed.extract()

    _insert_run(soup, merged_root, run)

    for group in root_groups:
        r = group["root"]
        if r.parent is not None and _is_empty_wrapper(r):
            r.decompose()


def merge_bullet_md(soup: BeautifulSoup) -> None:
    _merge_bullet_md_tabbed(soup, "bullet-md")
    _merge_bullet_md_untabbed(soup, "untabbed-bullet-md")


def unwrap_buttons_and_dialogs(soup: BeautifulSoup) -> None:
    for tag in soup.find_all(["button", "dialog"]):
        tag.name = "div"


def restructure_details_accordions(soup: BeautifulSoup) -> None:
    for details in soup.find_all("details"):
        summary = details.find("summary")
        if summary is None:
            continue
        heading = soup.new_tag("h3")
        heading.string = summary.get_text(strip=True)
        summary.replace_with(heading)
        details.name = "div"


class SyllabusMarkdownConverter(MarkdownConverter):

    def convert_a(self, el, text, parent_tags=None, **kwargs):
        href = el.get("href") or ""
        if not text.strip() and not href:
            return ""
        return super().convert_a(el, text, parent_tags, **kwargs) if parent_tags is not None \
            else super().convert_a(el, text, **kwargs)


def html_to_markdown(html: str, base_dir: Path = None) -> str:
    soup = BeautifulSoup(html, "html.parser")

    inject_schedule_data(soup, base_dir if base_dir is not None else Path("."))
    strip_decorative_and_excluded(soup)
    restructure_pyramid_tiers(soup)
    clean_resource_cards(soup)
    clean_week_numbers(soup)
    clean_tag_rows(soup)
    merge_bullet_md(soup)
    restructure_details_accordions(soup)
    unwrap_buttons_and_dialogs(soup)

    body = soup.body or soup

    converter = SyllabusMarkdownConverter(
        heading_style="ATX",
        bullets="-",
        strip=["span"],  # unwrap spans (keep their text, drop the tag)
    )
    md = converter.convert_soup(body)

    sentinel_gap = re.compile(r"\n*" + re.escape(BULLET_MD_SENTINEL) + r"\n*")
    md = sentinel_gap.sub("\n", md)

    md = re.sub(r"[ \t]+\n", "\n", md)
    md = re.sub(r"\n{3,}", "\n\n", md)

    heading_or_hr_re = re.compile(r"^(#{1,6}\s|---$)")
    lines = md.split("\n")
    fixed = []
    for i, line in enumerate(lines):
        if i > 0 and heading_or_hr_re.match(
                line) and fixed and fixed[-1].strip() != "":
            fixed.append("")
        fixed.append(line)
    md = "\n".join(fixed)

    md = md.strip() + "\n"
    return md


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("index.html")
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else src.with_suffix(".md")

    html = src.read_text(encoding="utf-8")
    md = html_to_markdown(html, base_dir=src.parent)
    dst.write_text(md, encoding="utf-8")
    print(f"Wrote {dst}")


if __name__ == "__main__":
    main()